### ISSUE TITLE
Function names seem to be unreadable blocks

### ISSUE THREAD

**Issue by jryans** [akkartik/teliva#1]
When trying this out on macOS with iTerm2 and my usual theme, the function names seem to be the same colour as the block, so I can't read them.

Perhaps it's a terminal configuration issue...?

![image](https://user-images.githubusercontent.com/279572/144451006-d8bd654a-65d0-41d0-9137-2443310fd742.png)

**Comment by jryans** [comment]
Ah yeah, it looks okay in Terminal:

![image](https://user-images.githubusercontent.com/279572/144451731-bf3e6e5e-6b07-44a9-b4aa-32c8f44839b8.png)

So, maybe my theme is confused...

**Comment by jryans** [comment]
Ah yeah, looks like my default theme use the same colour for both foreground text and ANSI normal white, so perhaps it's something like that.

**Comment by akkartik** [comment]
@jryans and @khinsen, could you try now and check if the colors look better? (The other issues you reported aren't fixed yet.)

**Comment by akkartik** [comment]
@s-ol

**Comment by jryans** [comment]
Well, some improvement for me... Function names are readable now, but the code editor contrast has plummeted (yellow keywords blend in with the background now). Theming is hard... 😅 

![image](https://user-images.githubusercontent.com/279572/144862510-e7221e39-15a2-4da3-a121-7d676aa6b452.png)

![image](https://user-images.githubusercontent.com/279572/144862575-b690255f-127c-4a1a-89b3-091f133aa7ea.png)

**Comment by akkartik** [comment]
Ugh, thanks a lot.

Immediately I have two reactions:

* Perhaps I should assume at least 256 colors. 16 is too constrained, and so people tweak the 16 colors. (As is happening here? They're not so illegible on my terminal..)
* If I'm going to be constrained to 16 colors, perhaps a dark background is best.

Thoughts? My focus is on giving a good experience out of the box to anybody running a default LTS OS from say the past 5 years.

**Comment by khinsen** [comment]
I get the same colors as @jryans (I just posted similar screenshots on the FoC Slack.) 256 colors looks very reasonable nowadays. But I can't help much more - my understanding of terminal color assignments is close to zero.

**Comment by jryans** [comment]
Yeah, I would say try going for 256 colours, I would assume it works well enough these days. I am however also not an expert with terminal colours.

**Comment by s-ol** [comment]
I can "third" 256 colors. I think I started unix-ing around ten 10-12 years ago and I'm pretty sure I never had an incompatible terminal (except maybe the linux vtty before launching a desktop?)
